# Generated by Django 5.1.2 on 2024-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module19_6', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Game',
                'managed': False,
            },
        ),
    ]
